apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgresql-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: postgresql-db
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: postgresql-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: db
        image: postgresql-database:10.0
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: v1
kind: Service
metadata:
  name: api-rest
  labels:
    app: rest-api
spec:
  ports:
    - port: 7676
      targetPort: 7676
      name: api-port
  selector:
    app: rest-api
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-rest
  labels:
    app: rest-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: api-rest
        image: api-gateway:v1
        ports:
        - containerPort: 7676
          name: api-port
---
apiVersion: v1
kind: Service
metadata:
  name: ui-api
  labels:
    app: web-ui-api
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: ui-api
  selector:
    app: web-ui-api
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ui-api
  labels:
    app: web-ui-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-ui-api
    spec:
      containers:
      - name: ui-api
        image: api-gateway:v1
        ports:
        - containerPort: 80
          name: web-ui-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-web
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: web-ui
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - name: web-ui-container
        image: html:v1
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-svc
  labels:
    app: web-ui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: web-ui
